FROM python:3.10-slim

# Install pipenv and dependencies for building some Python packages
RUN pip install pipenv && \
    apt-get update && \
    apt-get install -y build-essential

WORKDIR /app

# Copy Pipfile and Pipfile.lock from the parent directory
COPY ../Pipfile ../Pipfile.lock ./

# Install dependencies
RUN pipenv install --system --deploy

# Copy the rest of the application
COPY ../src /app/src
COPY ../templates /app/templates
COPY ../static /app/static

# Run the application
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
